let products = {
    vases: [
        {
            id: 1,
            series: "Sozia Wine Bottle",
            currency: "$",
            price: 105,
            imgUrl: "4.jpg",
            description: "Over the years, the timeless Sozia vase has become a genuine classic. Most people associate the vase with minimalis and functional design. Right now you are looking at the 15 cm coloured porcelain vases. The Sozia vase is available in a wide range of colours and sizes.",
            designer: "Sozia Porcelean",
            sku: 200775,
            colour: "multicolor",
            material: "porcelean",
            height: 15,
            unit: "cm"
        },
        {
            id: 2,
            series: "Neutral Ceramic Vase",
            currency: "$",
            price: 85,
            imgUrl: "3.jpg",
            description: "Bring peace, serenity, and balance to your space with Sage & Sill's Shades of Neutral Ceramic Vases. Made of stunning matte ceramic, these vases feature six unique designs that make a statement by themselves or in a group. Perfect for dried flowers, grasses, or florals, these vases are sure to elevate your decor and leave you feeling zen!",
            designer: "Sageandsill",
            sku: 206575,
            colour: "rose",
            material: "ceramic",
            height: 18,
            unit: "cm"
        },
        {
            id: 3,
            series: "Twist",
            currency: "$",
            price: 125,
            imgUrl: "2.jpg",
            description: "Sight Unseen references Renaissance paintings and historic French ceramics in this collection of pastel-toned and nude porcelain plates and vases",
            designer: "Sight Unseen",
            sku: 312775,
            colour: "nude",
            material: "ceramic",
            height: 20,
            unit: "cm"
        },
        {
            id: 4,
            series: "Rayne Abstract Vase",
            currency: "$",
            price: 115,
            imgUrl: "1.jpg",
            description: "The crisp lines and sharp angles of these striking ceramic vases bring a sense of artful sophistication to a tabletop, shelf, or mantel. Display flowers or use them as a focal point in your decor, these vases are compliment worthy.",
            designer: "Letifly",
            sku: 222775,
            colour: "black",
            material: "ceramic",
            height: 15,
            unit: "cm"
        }
    ],
    lamps: [
        {
            id: 1,
            series: "Fancy Lamp",
            currency: "$",
            price: 45,
            imgUrl: "4.jpg",
            description: "Over the years, the timeless Sozia vase has become a genuine classic. Most people associate the vase with minimalis and functional design. Right now you are looking at the 15 cm coloured porcelain vases. The Sozia vase is available in a wide range of colours and sizes.",
            designer: "Sozia Porcelean",
            sku: 200775,
            colour: "multicolor",
            material: "porcelean",
            height: 15,
            unit: "cm"
        },
        {
            id: 2,
            series: "Bedside Lamp",
            currency: "$",
            price: 55,
            imgUrl: "3.jpg",
            description: "Bring peace, serenity, and balance to your space with Sage & Sill's Shades of Neutral Ceramic Vases. Made of stunning matte ceramic, these vases feature six unique designs that make a statement by themselves or in a group. Perfect for dried flowers, grasses, or florals, these vases are sure to elevate your decor and leave you feeling zen!",
            designer: "Sageandsill",
            sku: 206575,
            colour: "rose",
            material: "ceramic",
            height: 18,
            unit: "cm"
        },
        {
            id: 3,
            series: "Desk Lamp",
            currency: "$",
            price: 155,
            imgUrl: "2.jpg",
            description: "Sight Unseen references Renaissance paintings and historic French ceramics in this collection of pastel-toned and nude porcelain plates and vases",
            designer: "Sight Unseen",
            sku: 312775,
            colour: "nude",
            material: "ceramic",
            height: 20,
            unit: "cm"
        },
        {
            id: 4,
            series: "Wooden Lamp",
            currency: "$",
            price: 115,
            imgUrl: "1.jpg",
            description: "The crisp lines and sharp angles of these striking ceramic vases bring a sense of artful sophistication to a tabletop, shelf, or mantel. Display flowers or use them as a focal point in your decor, these vases are compliment worthy.",
            designer: "Letifly",
            sku: 222775,
            colour: "black",
            material: "ceramic",
            height: 15,
            unit: "cm"
        }
    ],
    glasses: [
        {
            id: 1,
            series: "Collins Glass",
            currency: "$",
            price: 10,
            imgUrl: "3.jpg",
            description: "Over the years, the timeless Sozia vase has become a genuine classic. Most people associate the vase with minimalis and functional design. Right now you are looking at the 15 cm coloured porcelain vases. The Sozia vase is available in a wide range of colours and sizes.",
            designer: "Sozia Porcelean",
            sku: 200775,
            colour: "transparent",
            material: "glass",
            height: 15,
            unit: "cm"
        },
        {
            id: 2,
            series: "Delmonico Glass",
            currency: "$",
            price: 5,
            imgUrl: "2.jpg",
            description: "Bring peace, serenity, and balance to your space with Sage & Sill's Shades of Neutral Ceramic Vases. Made of stunning matte ceramic, these vases feature six unique designs that make a statement by themselves or in a group. Perfect for dried flowers, grasses, or florals, these vases are sure to elevate your decor and leave you feeling zen!",
            designer: "Sageandsill",
            sku: 206575,
            colour: "transparent",
            material: "glass",
            height: 18,
            unit: "cm"
        },
        {
            id: 3,
            series: "Wine Glass",
            currency: "$",
            price: 8,
            imgUrl: "1.jpg",
            description: "Sight Unseen references Renaissance paintings and historic French ceramics in this collection of pastel-toned and nude porcelain plates and vases",
            designer: "Sight Unseen",
            sku: 312775,
            colour: "transparent",
            material: "glass",
            height: 20,
            unit: "cm"
        },
        {
            id: 3,
            series: "Cocktail Glass",
            currency: "$",
            price: 12,
            imgUrl: "4.jpg",
            description: "Sight Unseen references Renaissance paintings and historic French ceramics in this collection of pastel-toned and nude porcelain plates and vases",
            designer: "Sight Unseen",
            sku: 312775,
            colour: "transparent",
            material: "glass",
            height: 20,
            unit: "cm"
        },
    ],
    accessories: [
        {
            id: 1,
            series: "Leaves Statue",
            currency: "$",
            price: 299,
            imgUrl: "1.jpg",
            description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse similique qui, quaerat quos officiis in quia iste odit ipsum ducimus aspernatur veniam asperiores porro, non distinctio autem nulla magnam ratione!",
            designer: "Virgil Abloh",
            sku: 200775,
            colour: "black",
            material: "porcelean",
            height: 8,
            unit: "cm"
        },
        {
            id: 2,
            series: "Luxury Tree Canvas",
            currency: "$",
            price: 599,
            imgUrl: "2.jpg",
            description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse similique qui, quaerat quos officiis in quia iste odit ipsum ducimus aspernatur veniam asperiores porro, non distinctio autem nulla magnam ratione!",
            designer: "Virgil Abloh",
            sku: 206575,
            colour: "golden",
            material: "ceramic",
            height: 20,
            unit: "cm"
        },
        {
            id: 3,
            series: "Thinker Mask Figures",
            currency: "$",
            price: 132,
            imgUrl: "3.jpg",
            description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse similique qui, quaerat quos officiis in quia iste odit ipsum ducimus aspernatur veniam asperiores porro, non distinctio autem nulla magnam ratione!",
            designer: "Virgil Abloh",
            sku: 312775,
            colour: "black",
            material: "leather",
            height: 10,
            unit: "cm"
        },
        {
            id: 4,
            series: "Royal Pineapples",
            currency: "$",
            price: 59,
            imgUrl: "4.jpg",
            description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse similique qui, quaerat quos officiis in quia iste odit ipsum ducimus aspernatur veniam asperiores porro, non distinctio autem nulla magnam ratione!",
            designer: "Virgil Abloh",
            sku: 312775,
            colour: "black",
            material: "leather",
            height: 10,
            unit: "cm"
        },
        {
            id: 5,
            series: "Modern Mirror",
            currency: "$",
            price: 100,
            imgUrl: "5.jpg",
            description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse similique qui, quaerat quos officiis in quia iste odit ipsum ducimus aspernatur veniam asperiores porro, non distinctio autem nulla magnam ratione!",
            designer: "Virgil Abloh",
            sku: 312775,
            colour: "black",
            material: "leather",
            height: 10,
            unit: "cm"
        }
    ]
}